name: Warp Team Tempalte
description: Primarily used for creating new issues based on a comment in another issue.
title: "[Warp Staff Template]"
body:
  - type: markdown
    attributes:
      value: |
        GitHub username
  - type: textarea
    attributes:
      value: Username
      label: username
  - type: markdown
    attributes:
      value: |
        URL / Link
  - type: textarea
    attributes:
      value: URL / Link
      label: URL / Link
  - type: markdown
    attributes:
      value: |
        The issue
  - type: textarea
    attributes:
      value: New issue!
      label: New issue
