name: Warp Team Template
description: Primarily used for creating new issues based on a comment in another issue.
title: "[Warp Staff Template]"
body:
  - type: input  
    id: "github_username"
    attributes:
      label: "GitHub username"
      description: github_username
      placeholder: username
    validations:
      required: false
  - type: input
    attributes:
      placeholder: URL
      label: url
  - type: textarea
    attributes:
      placeholder: Description of new issue
      label: issue_description