blank_issues_enabled: false
contact_links:
  - name: Warp Issue Search
    url: https://github.com/warpdotdev/warp/issues?q=is%3Aissue+sort%3Acreated-asc+
    about: Search Warp's issues and feature requests.
  - name: Documentation
    url: https://docs.warp.dev/help/known-issues?q=
    about: Documentation for full telemetry table, known issues, troubleshooting, features, and more!
  - name: Discord
    url: https://discord.gg/warpdotdev
    about: Discuss what you want to see in a modern terminal, report bugs, and brainstorm features for Warp.
  - name: Warp Homepage
    url: https://www.warp.dev/
    about: Warps website.
  - name: Blog
    url: https://blog.warp.dev/
    about: See our blog.
  - name: Changelog
    url: https://docs.warp.dev/help/changelog
    about: See our changelog.
  - name: Licenses
    url: https://docs.warp.dev/help/licenses
    about: See the projects that we depend on and their open source licenses.
